name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate Firebase
        run: firebase login:ci
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }} # Создайте секрет в настройках репозитория

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting
